### ISSUE TITLE
Datasource provisioning doesn't preserve password for basic auth

### ISSUE THREAD

**Issue by lainiwa** [Altinity/clickhouse-grafana#434]
I'm using this snippet for datasource provisioning:
```yml
apiVersion: 1
datasources:
    - name: ClickHouse
      type: vertamedia-clickhouse-datasource
      access: proxy
      basicAuth: true
      basicAuthUser: admin
      basicAuthPassword: nimda
      url: http://click:8443
      editable: true
```

Then I go to datasources, open ClickHouse datasource, and press "Save & test".
Getting the following:
```
Code: 516. DB::Exception: admin: Authentication failed: password is incorrect or there is no user with such name. (AUTHENTICATION_FAILED) (version 22.3.7.28 (official build)) 
```

However, the field `Password` under `Basic Auth Details` is empty and not "configured" as it should be.
When I insert `nimda` into that field and test it again, and it works: `Data source is working`.

My grafana version is v9.0.2 (0641b5d0cd).

Possibly related to #366.
