### ISSUE TITLE
Error: ✗ Plugin isn't available for your version of Grafana

### ISSUE THREAD

**Issue by vavilenski** [Altinity/clickhouse-grafana#439]
When I try to update my kubernetes grafana instance, I get next error in logs::

```
✔ Downloaded camptocamp-prometheus-alertmanager-datasource v1.2.1 zip successfully

Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.

✔ Downloaded grafana-piechart-panel v1.6.2 zip successfully

Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.

✔ Downloaded vertamedia-clickhouse-datasource v2.5.0 zip successfully

Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.

Error: ✗ Plugin isn't available for your version of Grafana (Grafana v9.0.0 linux-amd64)
```

Will this plugin work for Grafana >= 9.0.0 ?
Thank's for your time.

**Comment by Zeratyl06** [comment]
I have the same problem
![vertamedia-clickhouse-datasource](https://user-images.githubusercontent.com/19567341/184582413-5a1e8692-9b7d-4473-84e2-a43ef00cf896.jpg)

**Comment by Slach** [comment]
looks strange
altinity grafana plugin tested with Grafana 9.x and should works fine
![image](https://user-images.githubusercontent.com/105560/185791986-9cc3ef76-c16e-4151-b53c-b1313df02170.png)

Could you provide more context?
how do you try to install this plugin in your environment?

**Comment by Zeratyl06** [comment]
Of course. The plugin doesn't work for me, with an error in the grafana ui "Failed to evaluate queries and expressions: failed to execute conditions: plugin unavailable".
```
x-services-options: &service_options
  restart: unless-stopped
  cap_drop:
    - NET_ADMIN
    - SYS_ADMIN
  security_opt:
    - no-new-privileges

services:
  grafana:
    <<: *service_options
    container_name: grafana
    image: grafana/grafana:9.0.6
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./grafana/ldap.toml:/etc/grafana/ldap.toml:ro
      - ./grafana/data:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: vertamedia-clickhouse-datasource,grafana-piechart-panel,flant-statusmap-panel,camptocamp-prometheus-alertmanager-datasource,alexanderzobnin-zabbix-app
      GF_SERVER_ROOT_URL: 'https://{{ nginx_site_fqdn }}'
      GF_SESSION_COOKIE_SECURE: 'true'
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: '{{ grafana_admin_password }}'
      GF_SECURITY_COOKIE_SECURE: 'true'
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_AUTH_LDAP_ENABLED: 'true'
      GF_AUTH_LDAP_CONFIG_FILE: '/etc/grafana/ldap.toml'
      GF_LOG_CONSOLE_FORMAT: json
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: 'vertamedia-clickhouse-datasource'
```
![image](https://user-images.githubusercontent.com/19567341/185793348-2c6e1761-d50d-49be-8af0-213524e7ff44.png)
