### ISSUE TITLE
Documentation: Fix the structure of yaml [Configure the Datasource with Provisioning]

### ISSUE THREAD

**Issue by mrlexor** [Altinity/clickhouse-grafana#452]
Hello,

In the current repo and in Grafana [docs](https://grafana.com/grafana/plugins/vertamedia-clickhouse-datasource/) you have different example of describing datasource via yaml.

It is example from Grafana [docs](https://grafana.com/grafana/plugins/vertamedia-clickhouse-datasource/):
```Yaml
apiVersion: 1
datasources:


name: Clickhouse
type: vertamedia-clickhouse-datasource
access: proxy
url: http://localhost:8123
<bool> enable/disable basic auth
basicAuth:
<string> basic auth username
basicAuthUser:
<string> basic auth password
basicAuthPassword:
<bool> enable/disable with credentials headers
withCredentials:
<bool> mark as default datasource. Max one per org
isDefault:
<map> fields that will be converted to json and stored in json_data
jsonData:
<bool> enable/disable sending ‘add_http_cors_header=1’ parameter
addCorsHeader:
<bool> enable/disable using POST method for sending queries
usePOST:
<string> default database name
defaultDatabase:
```

Where I see mistakes about `basicAuthPassword` and `usePOST`.

`basicAuthPassword` must be placed inside the `secureJsonData` while `usePOST` inside the `jsonData` dictionaries.

Almost the same mistake also you have in `README.md`:

```Yaml
apiVersion: 1

datasources:
 - name: Clickhouse
   type: vertamedia-clickhouse-datasource
   access: proxy
   url: http://localhost:8123

   # <bool> enable/disable basic auth
   basicAuth:
   # <string> basic auth username
   basicAuthUser:
   # <string> basic auth password
   basicAuthPassword:
   # <bool> enable/disable with credentials headers
   withCredentials:
   # <bool> mark as default datasource. Max one per org
   isDefault:
   # <map> fields that will be converted to json and stored in json_data
   jsonData:
      # <bool> enable/disable sending 'add_http_cors_header=1' parameter
      addCorsHeader:
      # <bool> enable/disable using POST method for sending queries
      usePOST:
      # <string> default database name
      defaultDatabase:
```

Here you just need to move `basicAuthPassword` inside the `secureJsonData` dictionary. At the end in both places you need to describe the following structure for well working datasource provisioning:

```Yaml
- name: "Clickhouse"
  type: vertamedia-clickhouse-datasource
  uid: clickhouse
  url: http://host:port
  basicAuth: true
  withCredentials: true
  basicAuthUser: "username"
  secureJsonData:
    basicAuthPassword: "password"
  jsonData:
    usePOST: true
    addCorsHeader: ""
    defaultDatabase: ""
```

[Here](https://github.com/Altinity/clickhouse-grafana/blob/1af3b4d1d7df812aceb1d42c2f5592aa8af192c4/pkg/client.go#L57) and [here](https://github.com/Altinity/clickhouse-grafana/blob/574cda7d33c064948bd78fbc272b3eee42340f16/src/datasource.ts#L49) you can find the proofs.
